name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e  # Остановит скрипт при любой ошибке
            cd /home/bayar/bayar-frontend
            echo "Pulling latest changes..."
            git pull origin main
            echo "Installing dependencies..."
            npm ci
            echo "Building project..."
            npm run build
            echo "Restarting PM2..."
            pm2 restart frontend
            echo "✅ Deployment successful!" > deployment.log

      - name: Send success email
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: '✅ Deployment Successful for ${{ github.repository }}'
          body: "The deployment for ${{ github.repository }} was successful! 🎉\n\nCheck it out here: https://tatbayar.ru"
          to: 'timur.salakhutdinov@gmail.com'
          from: ${{ secrets.SMTP_FROM }}

      - name: Send failure email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: '❌ Deployment Failed for ${{ github.repository }}'
          body: "The deployment for ${{ github.repository }} failed. ❗\n\nCheck the logs here: ${{ github.run_url }}"
          to: 'timur.salakhutdinov@gmail.com'
          from: ${{ secrets.SMTP_FROM }}
